-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

--- writing the schema for SoftCart schema

BEGIN;

-- Dimension table softcartDimDate desing
CREATE TABLE public."softcartDimDate"
(
    date_id integer NOT NULL, 
    date date NOT NULL, 
    day integer NOT NULL, 
    weekday integer NOT NULL, 
    weekday_name varchar(20) NOT NULL,
    month integer NOT NULL,
    month_name varchar(20) NOT NULL, 
    year integer NOT NULL,
    quarter integer NOT NULL, 
    quarter_name varchar(20) NOT NULL,
    PRIMARY KEY (date_id)
);


-- Dimension table softcartDimCategory design
CREATE TABLE public."softcartDimCategory"
(
    category_id integer NOT NULL, 
    category_name varchar(20) NOT NULL, 
    PRIMARY KEY (category_id)
);


-- Dimension table softcartDimItem design
CREATE TABLE public."softcartDimItem"
(
    item_id integer NOT NULL, 
    item_name varchar(20) NOT NULL, 
    PRIMARY KEY (item_id)
);


-- Dimension table softcartDimCountry design
CREATE TABLE public."softcartDimCountry"
(
    country_id integer NOT NULL, 
    country_name varchar(20) NOT NULL, 
    PRIMARY KEY (country_id)
);


-- Dimension table softcartFactSales design
CREATE TABLE public."softcartFactSales"
(
    order_id integer NOT NULL,
    item_id integer NOT NULL,
    category_id integer NOT NULL,
    price integer NOT NULL,
    country_id integer NOT NULL,
    date_id integer NOT NULL,
    FOREIGN KEY (item_id) REFERENCES public."softcartDimItem"(item_id),
    FOREIGN KEY (category_id) REFERENCES public."softcartDimCategory"(category_id),
    FOREIGN KEY (country_id) REFERENCES public."softcartDimCountry"(country_id),
    FOREIGN KEY (date_id) REFERENCES public."softcartDimDate"(date_id)
);



END;